# Generated by Django 4.2.4 on 2023-08-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_employee_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestatus',
            options={'verbose_name': 'Device Status', 'verbose_name_plural': 'Device Status'},
        ),
        migrations.RenameField(
            model_name='devicelog',
            old_name='check_in_datetime',
            new_name='check_in_at',
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='status_when_checked_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_checkin_status', to='asset.devicestatus'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='status_when_returned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_return_status', to='asset.devicestatus'),
        ),
    ]
