# Generated by Django 4.2.4 on 2023-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_devicestatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='type',
            field=models.CharField(choices=[('checkin', 'Check In'), ('checkout', 'Check Out')], max_length=20, null=True),
        ),
    ]
