# Generated by Django 4.2.4 on 2023-08-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_devicelog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='assigned_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
